[package]
name = "infiltrator-admin"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }
infiltrator-application = { path = "../infiltrator-application" }
infiltrator-contract = { path = "../infiltrator-contract" }
infiltrator-domain = { path = "../infiltrator-domain" }
infiltrator-http = { path = "../infiltrator-http" }
infiltrator-ports = { path = "../infiltrator-ports" }
infiltrator-shared = { path = "../infiltrator-shared" }
log = { workspace = true }
mihomo-config = { path = "../mihomo-config" }
mihomo-platform = { path = "../mihomo-platform" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
tower-http = { workspace = true, features = ["fs"] }
tower = { version = "0.5", features = ["util"] }
url = { workspace = true }

[dev-dependencies]
infiltrator-core = { path = "../infiltrator-core" }
mihomo-api = { path = "../mihomo-api" }
tempfile = { workspace = true }
mockito = { workspace = true }
