//! The application-wide [`Message`] bus plus its compact `Debug`
//! implementation used by tracing and tests.

use super::app::{
    ConfirmAction, CoreDownloadProgress, Route, SyncProgress, SyncSummary, ToastStatus,
};
use super::dns::{AdvancedConfigsBundle, AdvancedEditMode, DnsTab};
use super::rules::{RulesJsonTab, RulesLoadBundle, RulesTab};
use super::runtime::{IpProbeResult, RuntimeConfig, RuntimeStreamKind, RuntimeStreamState};
use iced::{widget::text_editor, window};
use infiltrator_core::error::InfiltratorError;
use infiltrator_domain::rules::RuleEntry;
use infiltrator_desktop::runtime::MihomoRuntime;
use mihomo_api::types::{ConnectionSnapshot, TrafficData};
use mihomo_config::profile::Profile;
use mihomo_version::manager::VersionInfo;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

/// Per-profile outcome list of the tray-driven "update all subscriptions"
/// entry: `(profile name, update result)` per refreshed subscription.
pub type SubscriptionUpdateOutcomes = Result<Vec<(String, Result<(), String>)>, InfiltratorError>;

#[derive(Clone)]
pub enum Message {
    Noop,
    Navigate(Route),
    NavigateBack,
    NavigateForward,
    StartProxy,
    StopProxy,
    /// Core boot result; the bool reports whether the external-controller
    /// port had to be rotated during the boot retry loop.
    ProxyStarted(Result<(Arc<MihomoRuntime>, bool), InfiltratorError>, u64),
    ProxyStopped,
    SettingsLoaded(Result<infiltrator_core::settings::AppSettings, InfiltratorError>),
    LoadProfiles,
    ProfilesLoaded(Result<Vec<Profile>, InfiltratorError>),
    SetActiveProfile(String),
    ProfileActivationFinished(Result<bool, InfiltratorError>),
    UpdateImportUrl(String),
    UpdateImportName(String),
    UpdateImportActivate(bool),
    ImportProfile,
    ProfileImported(Result<bool, InfiltratorError>),
    DeleteProfile(String),
    ProfileDeleted(Result<(), InfiltratorError>),
    UpdateLocalImportPath(String),
    BrowseLocalImportFile,
    LocalImportFilePicked(Option<PathBuf>),
    UpdateLocalImportName(String),
    UpdateLocalImportActivate(bool),
    ImportLocalProfile,
    LocalProfileImported(Result<bool, InfiltratorError>),
    SelectSubscriptionProfile(String),
    UpdateSubscriptionUrl(String),
    UpdateSubscriptionAutoUpdate(bool),
    UpdateSubscriptionInterval(String),
    UpdateSubscriptionUserAgent(String),
    SaveSubscriptionSettings,
    SubscriptionSettingsSaved(Result<(), InfiltratorError>),
    UpdateSubscriptionNow,
    SubscriptionUpdatedNow(Result<bool, InfiltratorError>),
    SubscriptionAutoUpdated(Result<(Vec<String>, bool), InfiltratorError>),
    // Tray entries: update every subscription now (ignoring schedules) and
    // flip one profile's auto-update flag straight from the menu.
    UpdateAllSubscriptionsNow,
    AllSubscriptionsUpdated(SubscriptionUpdateOutcomes),
    SetProfileAutoUpdate {
        name: String,
        enabled: bool,
    },
    ProfileAutoUpdateSet(Result<String, InfiltratorError>),
    UpdateProfilesFilter(String),
    ClearProfiles,
    ProfilesCleared(Result<(), InfiltratorError>),
    LoadProxies,
    ProxiesLoaded(Result<HashMap<String, mihomo_api::proxy::types::Proxy>, InfiltratorError>),
    SelectProxy(String, String),
    FilterProxies(String),
    ToggleFilterAlive(bool),
    ToggleFavoriteProxy(String),
    ToggleProxyCompactView,
    InspectProxy(Option<String>),
    OpenAddCustomNodeModal(bool),
    UpdateNewNodeType(String),
    UpdateNewNodeName(String),
    UpdateNewNodeServer(String),
    UpdateNewNodePort(String),
    UpdateNewNodeCredential(String),
    UpdateNewNodeCipher(String),
    UpdateNewNodeTls(bool),
    SubmitAddCustomNode,
    CustomNodeAdded(Result<(), InfiltratorError>),
    ToggleProxySort,
    UpdateProxyDelaySort(String),
    UpdateDelayTestUrl(String),
    UpdateDelayTimeoutMs(String),
    UpdateRuntimeSelectedGroup(String),
    UpdateRuntimeSelectedProxy(String),
    ApplyRuntimeSelectedProxy,
    UpdateRuntimeConnectionFilter(String),
    UpdateRuntimeConnectionSort(String),
    RefreshRuntimeNow,
    TrafficReceived(TrafficData),
    MemoryReceived(mihomo_api::types::MemoryData),
    IpInfoReceived(Result<IpProbeResult, InfiltratorError>, usize),
    ConnectionsReceived(ConnectionSnapshot),
    LogReceived(String),
    RuntimeStreamLogReceived(u64, String),
    RuntimeStreamTrafficReceived(u64, TrafficData),
    RuntimeStreamConnectionsReceived(u64, ConnectionSnapshot),
    RuntimeStreamStateChanged {
        kind: RuntimeStreamKind,
        generation: u64,
        state: RuntimeStreamState,
    },
    RuntimePollFailed(String),
    ClearRuntimeLogs,
    SetLogLevel(String),
    CloseConnection(String),
    CloseAllConnections,
    ConnectionsPrevPage,
    ConnectionsNextPage,
    FetchRuntimeConfig,
    FetchIpInfo,
    RuntimeConfigFetched(Result<RuntimeConfig, InfiltratorError>, u64),
    SetProxyMode(String),
    SetTunEnabled(bool),
    InstallTunService,
    RefreshTunServiceStatus,
    TunServiceStatusLoaded(
        Result<infiltrator_desktop::tun_service::ServiceModeStatus, InfiltratorError>,
    ),
    TunServiceInstalled(Result<(), InfiltratorError>),
    SetTunStack(String),
    SetTunAutoRoute(bool),
    SetTunStrictRoute(bool),
    SetSnifferEnabled(bool),
    ModeSetResult(Result<(), InfiltratorError>),
    RuntimePatchResult(Result<(), InfiltratorError>, u64, u64),
    OperationResult(Result<(), InfiltratorError>),
    LoadRules,
    RulesBundleLoaded(Result<RulesLoadBundle, InfiltratorError>),
    RulesLoaded(Result<Vec<RuleEntry>, InfiltratorError>),
    SetRulesTab(RulesTab),
    SetRulesJsonTab(RulesJsonTab),
    ToggleRulesProvidersExpanded,
    RulesPrevPage,
    RulesNextPage,
    RulesSetPage(usize),
    EnsureRuleProvidersEditorLoaded,
    EnsureProxyProvidersEditorLoaded,
    EnsureSnifferEditorLoaded,
    ActivateRulesHeavyView,
    RuleProvidersJsonLoaded(Result<String, InfiltratorError>),
    ProxyProvidersJsonLoaded(Result<String, InfiltratorError>),
    SnifferJsonLoaded(Result<String, InfiltratorError>),
    LoadProviders,
    ProvidersLoaded(
        Result<
            (
                Vec<mihomo_api::types::ProxyProvider>,
                Vec<mihomo_api::types::RuleProvider>,
            ),
            InfiltratorError,
        >,
    ),
    UpdateProxyProvider(String),
    UpdateRuleProvider(String),
    FilterRules(String),
    UpdateRulesTracerInput(String),
    RunRulesTracer,
    UpdateFilteredGroups,
    UpdateNewRuleType(String),
    UpdateNewRulePayload(String),
    UpdateNewRuleTarget(String),
    AddCustomRule,
    RuleAdded(Result<(), InfiltratorError>),
    ToggleRuleEnabled(usize),
    MoveRuleUp(usize),
    MoveRuleDown(usize),
    SaveRules,
    ApplyGameRoutingPresets,
    UpdateGeoDatabases,
    GeoDatabasesUpdated(Result<(), InfiltratorError>),
    RulesSaved(Result<(), InfiltratorError>),
    InspectRuleProviderDiff(Option<String>),
    UnpackRuleProvider(String),
    RuleProviderDiffLoaded(Result<infiltrator_domain::rules::RuleProviderDiff, InfiltratorError>),
    RuleProvidersEditorAction(text_editor::Action),
    SaveRuleProvidersJson,
    RuleProvidersJsonSaved(Result<(), InfiltratorError>),
    ProxyProvidersEditorAction(text_editor::Action),
    SaveProxyProvidersJson,
    ProxyProvidersJsonSaved(Result<(), InfiltratorError>),
    SnifferEditorAction(text_editor::Action),
    SaveSnifferJson,
    SnifferJsonSaved(Result<(), InfiltratorError>),
    LoadAdvancedConfigs,
    AdvancedConfigsBundleLoaded(Result<Box<AdvancedConfigsBundle>, InfiltratorError>),
    SetDnsTab(DnsTab),
    SetAdvancedMode(DnsTab, AdvancedEditMode),
    RefreshDnsOnly,
    RefreshFakeIpOnly,
    RefreshTunOnly,
    EnsureDnsEditorLoaded,
    EnsureFakeIpEditorLoaded,
    EnsureTunEditorLoaded,
    ActivateDnsHeavyView,
    DnsConfigJsonLoaded(Result<String, InfiltratorError>),
    FakeIpConfigJsonLoaded(Result<String, InfiltratorError>),
    TunConfigJsonLoaded(Result<String, InfiltratorError>),
    UpdateDnsFormEnable(bool),
    UpdateDnsFormNameserver(String),
    UpdateDnsFormFallback(String),
    UpdateDnsFormEnhancedMode(String),
    UpdateDnsFormFakeIpRange(String),
    UpdateDnsFormFakeIpFilter(String),
    UpdateDnsFormIpv6(bool),
    UpdateDnsFormCache(bool),
    UpdateDnsFormUseHosts(bool),
    UpdateDnsFormUseSystemHosts(bool),
    UpdateDnsFormRespectRules(bool),
    UpdateDnsFormProxyServerNameserver(String),
    UpdateDnsFormDirectNameserver(String),
    UpdateFakeIpFormRange(String),
    UpdateFakeIpFormFilter(String),
    UpdateFakeIpFormStore(bool),
    UpdateTunFormEnable(bool),
    UpdateTunFormStack(String),
    UpdateTunFormMtu(String),
    UpdateTunFormDnsHijack(String),
    UpdateTunFormAutoRoute(bool),
    UpdateTunFormAutoDetectInterface(bool),
    UpdateTunFormStrictRoute(bool),
    DnsConfigEditorAction(text_editor::Action),
    FakeIpConfigEditorAction(text_editor::Action),
    TunConfigEditorAction(text_editor::Action),
    TickSubUpdate,
    TickWebDavSync,
    TickRuntimeRefresh,
    TickFrame(Instant),
    TrayEvent(crate::tray::spec::TrayEvent),
    Exit,
    UpdateDnsServer(usize, String),
    UpdateDnsEnhancedMode(String),
    AddDnsServer,
    AddDnsServerTemplate(String),
    RemoveDnsServer(usize),
    UpdateFallbackDnsServer(usize, String),
    AddFallbackDnsServer,
    RemoveFallbackDnsServer(usize),
    SaveDns,
    DnsSaved(Result<(), InfiltratorError>),
    SaveFakeIpConfig,
    FakeIpConfigSaved(Result<(), InfiltratorError>),
    SaveTunConfig,
    TunConfigSaved(Result<(), InfiltratorError>),
    SetAutostart(bool),
    AutostartSet(Result<(), InfiltratorError>),
    UpdateNotificationsEnabled(bool),
    UpdateCloseToTray(bool),
    UpdateWebDavEnabled(bool),
    UpdateWebDavUrl(String),
    UpdateWebDavUser(String),
    UpdateWebDavPass(String),
    UpdateWebDavSyncInterval(String),
    UpdateWebDavSyncOnStartup(bool),
    SaveAppSettings,
    AppSettingsSaved(Result<(), InfiltratorError>),
    UpdateEditorPathSetting(String),
    SetAdminEnabled(bool),
    UpdateAdminPort(String),
    ApplyAdminSettings,
    AdminSettingsSaved(Result<(), InfiltratorError>),
    AdminServerStarted(Result<String, InfiltratorError>),
    AdminHostCommand(crate::admin_server::AdminHostCommand),
    ExternalSettingsLoaded(Result<infiltrator_core::settings::AppSettings, InfiltratorError>),
    SyncUpload,
    SyncDownload,
    SyncFinished(Result<SyncSummary, InfiltratorError>),
    SyncProgress(SyncProgress),
    ResolveSyncConflict(String),
    DismissSyncConflict(String),
    SyncConflictResolved(Result<String, InfiltratorError>),
    SyncConflictDismissed(Result<String, InfiltratorError>),
    CancelWebDavSync,
    TestWebDavConnection,
    WebDavConnectionTested(Result<(), InfiltratorError>),
    SetSystemProxy(bool),
    UpdateSystemProxyBypass(String),
    SystemProxySet(Result<(), InfiltratorError>),
    RequestAdminPrivilege,
    RequestConfirmation(ConfirmAction),
    ConfirmAction,
    CancelConfirmation,
    ClearError,
    EditProfile(PathBuf),
    /// Open a profile in the Editor with a specific pane preselected
    /// (one-click 覆写/过滤 entry points).
    EditProfileAs(PathBuf, crate::types::options::EditorPane),
    ProfileContentLoaded(Result<(PathBuf, String), InfiltratorError>),
    LoadProfileSnapshots,
    ProfileSnapshotsLoaded(Result<Vec<infiltrator_core::history::SnapshotMeta>, InfiltratorError>),
    RestoreProfileSnapshot(PathBuf),
    ProfileSnapshotRestored(Result<(), InfiltratorError>),
    EditorAction(text_editor::Action),
    SaveProfile,
    ProfileSaved(Result<(), InfiltratorError>),
    // Profile options: mixin overlay editor (Editor page second pane).
    SetEditorPane(crate::types::options::EditorPane),
    MixinEditorAction(text_editor::Action),
    MixinLoaded(Result<String, InfiltratorError>),
    SaveMixin,
    MixinSaved(Result<(), InfiltratorError>),
    // Profile options: subscription filter editor (Profiles page card).
    LoadProfileFilter,
    ProfileFilterLoaded(Result<crate::types::options::FilterDraft, InfiltratorError>),
    UpdateFilterInclude(String),
    UpdateFilterExclude(String),
    UpdateFilterExcludeTypes(String),
    UpdateFilterRenames(String),
    UpdateFilterDedup(usize),
    SaveProfileFilter,
    ProfileFilterSaved(Result<infiltrator_domain::filter::FilterReport, InfiltratorError>),
    // MRS rule-provider detail scan (Rules page providers tab).
    ScanMrsProviders,
    MrsDetailsReady(Result<Vec<crate::types::options::MrsProviderDetail>, InfiltratorError>),
    // Sync conflict key-level diff merge (Sync page).
    LoadSyncDiff(String),
    SyncDiffLoaded(Result<crate::types::options::SyncDiffBundle, InfiltratorError>),
    PickSyncDiffKey(String, bool),
    SetSyncDiffPicks(bool),
    ApplySyncDiffMerge,
    SyncDiffMerged(Result<String, InfiltratorError>),
    CloseSyncDiff,
    OpenConfigDirFinished(Result<(), InfiltratorError>),
    LoadKernels,
    KernelsLoaded(Result<Vec<VersionInfo>, InfiltratorError>),
    CheckCoreUpdate,
    CoreUpdateInfo(Result<String, InfiltratorError>), // Latest version string
    SetCoreChannel(String),
    DownloadCore(String),
    CoreDownloadProgress(CoreDownloadProgress, u64),
    CoreDownloadFinished(Result<String, InfiltratorError>, u64),
    CancelCoreDownload,
    DeleteKernel(String),
    SetDefaultKernel(String),
    KernelOperationFinished(Result<(), InfiltratorError>),
    FactoryReset,
    FactoryResetFinished(Result<(), InfiltratorError>),
    OpenConfigDir,
    FlushFakeIpCache,
    TestProxyDelay(String),
    TestGroupDelay(String),
    ProxyTested(String, Result<u64, InfiltratorError>),
    WindowClosed(window::Id),
    HideWindow,
    ShowWindow,
    UpdateRuntimeAutoRefresh(bool),
    RuntimePanelSettingsSaved(Result<(), InfiltratorError>),
    RuntimeRebuildFinished(Result<Arc<MihomoRuntime>, InfiltratorError>),
    ClearRebuildFlow,
    TogglePerfPanel,
    ToggleTheme,
    SetTheme(String),
    SetLanguage(String),
    ShowToast(String, ToastStatus),
    RemoveToast(usize),
    TestAllProxyDelays,
    AllProxyDelaysTested(Result<(usize, usize), InfiltratorError>),
    // ui-wave2-p: proxies page — expand/collapse one proxy-group card
    // (view-only UI state; flips AppState::proxy_groups_expanded).
    ToggleProxyGroupExpanded(String),
    // Doctor 体检面板（诊断域）：经内嵌 admin server 的 loopback HTTP 调用
    // /admin/api/doctor* 与 /admin/api/bootstrap，报告写回 diag.doctor。
    RunDoctor,
    DoctorReportReady(Result<crate::types::doctor::DoctorReport, InfiltratorError>),
    RunDoctorFix,
    DoctorFixApplied(Result<crate::types::doctor::DoctorFixReport, InfiltratorError>),
    RunBootstrap,
    BootstrapFinished(Result<crate::types::doctor::BootstrapReport, InfiltratorError>),
    // Command Palette
    ToggleCommandPalette,
    OpenCommandPalette,
    CloseCommandPalette,
    SetCommandQuery(String),
    SelectNextCommand,
    SelectPrevCommand,
    ExecuteCommand(super::app::CommandAction),
    // Connection Deep Telemetry Inspector Drawer
    InspectConnection(Option<String>),
    CloseSingleConnection(String),
    // YAML Editor Snippets & Format
    InsertYamlSnippet(&'static str),
    FormatYamlEditor,
    // App Routing (应用分流)
    RefreshAppRoutingProcesses,
    AppRoutingProcessesLoaded(Vec<infiltrator_desktop::process_enumerator::ExtendedProcessInfo>),
    SetAppRoutingFilter(String),
    SetAppRoutingMode(super::app_routing::AppRoutingMode),
    SetAppRouteRule { process: String, rule: super::app_routing::AppRouteRule },
    SetAppRoutingCategory(Option<infiltrator_desktop::process_enumerator::ProcessCategory>),
    // Proxy Group Reorder (策略组重排)
    MoveProxyGroupUp(String),
    MoveProxyGroupDown(String),
    ResetProxyGroupOrder,
    // Mini HUD Mode (迷你网速悬浮窗)
    ToggleMiniHudMode,
    SetAlwaysOnTop(bool),
    // Script Sandbox Console (脚本沙箱控制台)
    RunScriptSandboxTest,
    SelectScriptPreset(String),
    UpdateScriptSandboxCode(String),
    UpdateScriptSandboxInputYaml(String),
    ClearScriptSandbox,
    // DNS Leak & Privacy Probe (Category 1)
    RunDnsLeakProbe,
    DnsLeakProbeFinished(super::dns::DnsLeakReport),
    // Custom Node Modal & Universal URI Codec (Category 2)
    OpenCustomNodeModal,
    CloseCustomNodeModal,
    UpdateCustomNodeUriInput(String),
    ParseAndImportCustomUri,
    ExportNodeAsUri(String),
    SaveCustomNodeForm,
    // Multi-Profile Aggregator (Category 3)
    OpenAggregatorModal,
    CloseAggregatorModal,
    ToggleAggregatorProfileSelection(String),
    UpdateAggregatorName(String),
    ExecuteProfileAggregation,
    // Connection Grouping & Quick Rule (Category 4)
    SetConnectionGroupingMode(super::runtime::ConnectionGroupingMode),
    AddQuickRuleFromConnection { pattern: String, target: String },
    // Config Snapshot Visual Diff & Rollback (Category 5)
    OpenSnapshotDiff(String),
    CloseSnapshotDiff,
    RollbackToSnapshot(String),
    // Global Hotkey Manager (Category 6)
    UpdateHotkeyCombo { id: String, combo: String },
    ToggleHotkeyEnabled(String),
    // Wave 3 Category 1: PCAP Exporter
    TogglePcapCapture,
    ExportPcapBuffer,
    // Wave 3 Category 2: Logical Sub-Rules Builder
    UpdateSubRuleOperator(String),
    AddSubRuleCondition(String),
    RemoveSubRuleCondition(usize),
    UpdateSubRuleTarget(String),
    InsertSubRuleIntoRules,
    // Wave 3 Category 3: Node Speedtest & Jitter
    RunNodeSpeedtest(String),
    NodeSpeedtestFinished(super::perf::SpeedtestResult),
    // Wave 3 Category 4: Geo Data Updater
    CheckGeoDataUpdates,
    TriggerGeoDataUpdate,
    GeoDataUpdateFinished(super::editor::GeoDataStatus),
    // Wave 3 Category 5: Windows UWP Loopback Utility
    ScanUwpApps,
    UwpAppsLoaded(Vec<super::app::UwpAppItem>),
    ExemptAllUwpApps,
    ClearAllUwpExemptions,
    ToggleUwpAppExemption(String),
    // Wave 3 Category 6: Encrypted Backup Package
    UpdateEncryptedBackupPassphrase(String),
    ExportEncryptedPackage,
    ImportEncryptedPackage,
    // Wave 4 Category 1: Network Interface Roaming
    PollNetworkInterfaces,
    NetworkInterfacesPolled(Vec<super::runtime::NetworkInterfaceItem>),
    ForceGatewayReconnect,
    // Wave 4 Category 2: Crash Watchdog & Forensics
    CheckCrashWatchdog,
    RecoverOrphanedState,
    ExportCrashDiagnostics,
    // Wave 4 Category 3: External Web Dashboard
    LaunchWebDashboard(&'static str),
    // Wave 4 Category 4: Log Regex & Redacted Export
    UpdateLogRegexFilter(String),
    SetLogLevelFilter(String),
    ExportRedactedLogs,
    // Wave 4 Category 5: Subscription Quota & Cron
    EvaluateSubscriptionQuota,
    UpdateCronScheduleHours(u32),
    // Wave 4 Category 6: PAC Auto-Proxy & Bypass CIDR
    UpdatePacBypassSubnets(String),
    CompileAndValidatePac,
    TogglePacMode(bool),
    // Wave 5 Category 1: Rule Hit Counter & Stale Rule Audit
    AuditStaleRules,
    DisableZeroHitRules,
    // Wave 5 Category 2: Latency Time-Series & Stability Radar
    SelectRadarNode(String),
    RecordRadarLatencySample { node: String, latency_ms: u64 },
    // Wave 5 Category 3: TUN Multi-Stack & MTU Negotiator
    SelectTunStack(String),
    ProbeOptimalMtu,
    MtuProbed(u32),
    // Wave 5 Category 4: Rule-Provider Lifecycle & Rule Unpacker
    UnpackRuleProviderToCustom(String),
    PurgeRuleProviderCache,
    // Wave 5 Category 5: Config Apply Multi-Stage Transaction Guard
    TriggerAtomicConfigApply,
    ApplyTransactionStageChanged(super::runtime::ApplyTransactionStage),
    // Wave 5 Category 6: LAN Proxy Sharing & Client Access Whitelist
    ToggleLanSharing(bool),
    UpdateLanSharingPort(u16),
    UpdateLanAclWhitelist(String),
}

mod debug;
