//! The application-wide [`Message`] bus plus its compact `Debug`
//! implementation used by tracing and tests.

use super::app::{
    ConfirmAction, CoreDownloadProgress, Route, SyncProgress, SyncSummary, ToastStatus,
};
use super::dns::{AdvancedConfigsBundle, AdvancedEditMode, DnsTab};
use super::rules::{RulesJsonTab, RulesLoadBundle, RulesTab};
use super::runtime::{IpProbeResult, RuntimeConfig, RuntimeStreamKind, RuntimeStreamState};
use iced::{widget::text_editor, window};
use infiltrator_core::error::InfiltratorError;
use infiltrator_core::rules::RuleEntry;
use infiltrator_desktop::runtime::MihomoRuntime;
use mihomo_api::types::{ConnectionSnapshot, TrafficData};
use mihomo_config::profile::Profile;
use mihomo_version::manager::VersionInfo;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

/// Per-profile outcome list of the tray-driven "update all subscriptions"
/// entry: `(profile name, update result)` per refreshed subscription.
pub type SubscriptionUpdateOutcomes =
    Result<Vec<(String, Result<(), String>)>, InfiltratorError>;

#[derive(Clone)]
pub enum Message {
    Noop,
    Navigate(Route),
    StartProxy,
    StopProxy,
    /// Core boot result; the bool reports whether the external-controller
    /// port had to be rotated during the boot retry loop.
    ProxyStarted(Result<(Arc<MihomoRuntime>, bool), InfiltratorError>, u64),
    ProxyStopped,
    SettingsLoaded(Result<infiltrator_core::settings::AppSettings, InfiltratorError>),
    LoadProfiles,
    ProfilesLoaded(Result<Vec<Profile>, InfiltratorError>),
    SetActiveProfile(String),
    ProfileActivationFinished(Result<bool, InfiltratorError>),
    UpdateImportUrl(String),
    UpdateImportName(String),
    UpdateImportActivate(bool),
    ImportProfile,
    ProfileImported(Result<bool, InfiltratorError>),
    DeleteProfile(String),
    ProfileDeleted(Result<(), InfiltratorError>),
    UpdateLocalImportPath(String),
    BrowseLocalImportFile,
    LocalImportFilePicked(Option<PathBuf>),
    UpdateLocalImportName(String),
    UpdateLocalImportActivate(bool),
    ImportLocalProfile,
    LocalProfileImported(Result<bool, InfiltratorError>),
    SelectSubscriptionProfile(String),
    UpdateSubscriptionUrl(String),
    UpdateSubscriptionAutoUpdate(bool),
    UpdateSubscriptionInterval(String),
    SaveSubscriptionSettings,
    SubscriptionSettingsSaved(Result<(), InfiltratorError>),
    UpdateSubscriptionNow,
    SubscriptionUpdatedNow(Result<bool, InfiltratorError>),
    SubscriptionAutoUpdated(Result<(Vec<String>, bool), InfiltratorError>),
    // Tray entries: update every subscription now (ignoring schedules) and
    // flip one profile's auto-update flag straight from the menu.
    UpdateAllSubscriptionsNow,
    AllSubscriptionsUpdated(SubscriptionUpdateOutcomes),
    SetProfileAutoUpdate {
        name: String,
        enabled: bool,
    },
    ProfileAutoUpdateSet(Result<String, InfiltratorError>),
    UpdateProfilesFilter(String),
    ClearProfiles,
    ProfilesCleared(Result<(), InfiltratorError>),
    LoadProxies,
    ProxiesLoaded(Result<HashMap<String, mihomo_api::proxy::types::Proxy>, InfiltratorError>),
    SelectProxy(String, String),
    FilterProxies(String),
    ToggleProxySort,
    UpdateProxyDelaySort(String),
    UpdateDelayTestUrl(String),
    UpdateDelayTimeoutMs(String),
    UpdateRuntimeSelectedGroup(String),
    UpdateRuntimeSelectedProxy(String),
    ApplyRuntimeSelectedProxy,
    UpdateRuntimeConnectionFilter(String),
    UpdateRuntimeConnectionSort(String),
    RefreshRuntimeNow,
    TrafficReceived(TrafficData),
    MemoryReceived(mihomo_api::types::MemoryData),
    IpInfoReceived(Result<IpProbeResult, InfiltratorError>, usize),
    ConnectionsReceived(ConnectionSnapshot),
    LogReceived(String),
    RuntimeStreamLogReceived(u64, String),
    RuntimeStreamTrafficReceived(u64, TrafficData),
    RuntimeStreamConnectionsReceived(u64, ConnectionSnapshot),
    RuntimeStreamStateChanged {
        kind: RuntimeStreamKind,
        generation: u64,
        state: RuntimeStreamState,
    },
    RuntimePollFailed(String),
    ClearRuntimeLogs,
    SetLogLevel(String),
    CloseConnection(String),
    CloseAllConnections,
    ConnectionsPrevPage,
    ConnectionsNextPage,
    FetchRuntimeConfig,
    FetchIpInfo,
    RuntimeConfigFetched(Result<RuntimeConfig, InfiltratorError>, u64),
    SetProxyMode(String),
    SetTunEnabled(bool),
    InstallTunService,
    RefreshTunServiceStatus,
    TunServiceStatusLoaded(
        Result<infiltrator_desktop::tun_service::ServiceModeStatus, InfiltratorError>,
    ),
    TunServiceInstalled(Result<(), InfiltratorError>),
    SetTunStack(String),
    SetTunAutoRoute(bool),
    SetTunStrictRoute(bool),
    SetSnifferEnabled(bool),
    ModeSetResult(Result<(), InfiltratorError>),
    RuntimePatchResult(Result<(), InfiltratorError>, u64, u64),
    OperationResult(Result<(), InfiltratorError>),
    LoadRules,
    RulesBundleLoaded(Result<RulesLoadBundle, InfiltratorError>),
    RulesLoaded(Result<Vec<RuleEntry>, InfiltratorError>),
    SetRulesTab(RulesTab),
    SetRulesJsonTab(RulesJsonTab),
    ToggleRulesProvidersExpanded,
    RulesPrevPage,
    RulesNextPage,
    RulesSetPage(usize),
    EnsureRuleProvidersEditorLoaded,
    EnsureProxyProvidersEditorLoaded,
    EnsureSnifferEditorLoaded,
    ActivateRulesHeavyView,
    RuleProvidersJsonLoaded(Result<String, InfiltratorError>),
    ProxyProvidersJsonLoaded(Result<String, InfiltratorError>),
    SnifferJsonLoaded(Result<String, InfiltratorError>),
    LoadProviders,
    ProvidersLoaded(
        Result<
            (
                Vec<mihomo_api::types::ProxyProvider>,
                Vec<mihomo_api::types::RuleProvider>,
            ),
            InfiltratorError,
        >,
    ),
    UpdateProxyProvider(String),
    UpdateRuleProvider(String),
    FilterRules(String),
    UpdateFilteredGroups,
    UpdateNewRuleType(String),
    UpdateNewRulePayload(String),
    UpdateNewRuleTarget(String),
    AddCustomRule,
    RuleAdded(Result<(), InfiltratorError>),
    ToggleRuleEnabled(usize),
    MoveRuleUp(usize),
    MoveRuleDown(usize),
    SaveRules,
    RulesSaved(Result<(), InfiltratorError>),
    RuleProvidersEditorAction(text_editor::Action),
    SaveRuleProvidersJson,
    RuleProvidersJsonSaved(Result<(), InfiltratorError>),
    ProxyProvidersEditorAction(text_editor::Action),
    SaveProxyProvidersJson,
    ProxyProvidersJsonSaved(Result<(), InfiltratorError>),
    SnifferEditorAction(text_editor::Action),
    SaveSnifferJson,
    SnifferJsonSaved(Result<(), InfiltratorError>),
    LoadAdvancedConfigs,
    AdvancedConfigsBundleLoaded(Result<Box<AdvancedConfigsBundle>, InfiltratorError>),
    SetDnsTab(DnsTab),
    SetAdvancedMode(DnsTab, AdvancedEditMode),
    RefreshDnsOnly,
    RefreshFakeIpOnly,
    RefreshTunOnly,
    EnsureDnsEditorLoaded,
    EnsureFakeIpEditorLoaded,
    EnsureTunEditorLoaded,
    ActivateDnsHeavyView,
    DnsConfigJsonLoaded(Result<String, InfiltratorError>),
    FakeIpConfigJsonLoaded(Result<String, InfiltratorError>),
    TunConfigJsonLoaded(Result<String, InfiltratorError>),
    UpdateDnsFormEnable(bool),
    UpdateDnsFormNameserver(String),
    UpdateDnsFormFallback(String),
    UpdateDnsFormEnhancedMode(String),
    UpdateDnsFormFakeIpRange(String),
    UpdateDnsFormFakeIpFilter(String),
    UpdateDnsFormIpv6(bool),
    UpdateDnsFormCache(bool),
    UpdateDnsFormUseHosts(bool),
    UpdateDnsFormUseSystemHosts(bool),
    UpdateDnsFormRespectRules(bool),
    UpdateDnsFormProxyServerNameserver(String),
    UpdateDnsFormDirectNameserver(String),
    UpdateFakeIpFormRange(String),
    UpdateFakeIpFormFilter(String),
    UpdateFakeIpFormStore(bool),
    UpdateTunFormEnable(bool),
    UpdateTunFormStack(String),
    UpdateTunFormMtu(String),
    UpdateTunFormDnsHijack(String),
    UpdateTunFormAutoRoute(bool),
    UpdateTunFormAutoDetectInterface(bool),
    UpdateTunFormStrictRoute(bool),
    DnsConfigEditorAction(text_editor::Action),
    FakeIpConfigEditorAction(text_editor::Action),
    TunConfigEditorAction(text_editor::Action),
    TickSubUpdate,
    TickWebDavSync,
    TickRuntimeRefresh,
    TickFrame(Instant),
    TrayEvent(crate::tray::spec::TrayEvent),
    Exit,
    UpdateDnsServer(usize, String),
    UpdateDnsEnhancedMode(String),
    AddDnsServer,
    AddDnsServerTemplate(String),
    RemoveDnsServer(usize),
    UpdateFallbackDnsServer(usize, String),
    AddFallbackDnsServer,
    RemoveFallbackDnsServer(usize),
    SaveDns,
    DnsSaved(Result<(), InfiltratorError>),
    SaveFakeIpConfig,
    FakeIpConfigSaved(Result<(), InfiltratorError>),
    SaveTunConfig,
    TunConfigSaved(Result<(), InfiltratorError>),
    SetAutostart(bool),
    AutostartSet(Result<(), InfiltratorError>),
    UpdateNotificationsEnabled(bool),
    UpdateWebDavEnabled(bool),
    UpdateWebDavUrl(String),
    UpdateWebDavUser(String),
    UpdateWebDavPass(String),
    UpdateWebDavSyncInterval(String),
    UpdateWebDavSyncOnStartup(bool),
    SaveAppSettings,
    AppSettingsSaved(Result<(), InfiltratorError>),
    UpdateEditorPathSetting(String),
    SetAdminEnabled(bool),
    UpdateAdminPort(String),
    ApplyAdminSettings,
    AdminSettingsSaved(Result<(), InfiltratorError>),
    AdminServerStarted(Result<String, InfiltratorError>),
    AdminHostCommand(crate::admin_server::AdminHostCommand),
    ExternalSettingsLoaded(Result<infiltrator_core::settings::AppSettings, InfiltratorError>),
    SyncUpload,
    SyncDownload,
    SyncFinished(Result<SyncSummary, InfiltratorError>),
    SyncProgress(SyncProgress),
    ResolveSyncConflict(String),
    DismissSyncConflict(String),
    SyncConflictResolved(Result<String, InfiltratorError>),
    SyncConflictDismissed(Result<String, InfiltratorError>),
    CancelWebDavSync,
    TestWebDavConnection,
    WebDavConnectionTested(Result<(), InfiltratorError>),
    SetSystemProxy(bool),
    SystemProxySet(Result<(), InfiltratorError>),
    RequestAdminPrivilege,
    RequestConfirmation(ConfirmAction),
    ConfirmAction,
    CancelConfirmation,
    ClearError,
    EditProfile(PathBuf),
    /// Open a profile in the Editor with a specific pane preselected
    /// (one-click 覆写/过滤 entry points).
    EditProfileAs(PathBuf, crate::types::options::EditorPane),
    ProfileContentLoaded(Result<(PathBuf, String), InfiltratorError>),
    LoadProfileSnapshots,
    ProfileSnapshotsLoaded(Result<Vec<infiltrator_core::history::SnapshotMeta>, InfiltratorError>),
    RestoreProfileSnapshot(PathBuf),
    ProfileSnapshotRestored(Result<(), InfiltratorError>),
    EditorAction(text_editor::Action),
    SaveProfile,
    ProfileSaved(Result<(), InfiltratorError>),
    // Profile options: mixin overlay editor (Editor page second pane).
    SetEditorPane(crate::types::options::EditorPane),
    MixinEditorAction(text_editor::Action),
    MixinLoaded(Result<String, InfiltratorError>),
    SaveMixin,
    MixinSaved(Result<(), InfiltratorError>),
    // Profile options: subscription filter editor (Profiles page card).
    LoadProfileFilter,
    ProfileFilterLoaded(Result<crate::types::options::FilterDraft, InfiltratorError>),
    UpdateFilterInclude(String),
    UpdateFilterExclude(String),
    UpdateFilterExcludeTypes(String),
    UpdateFilterRenames(String),
    UpdateFilterDedup(usize),
    SaveProfileFilter,
    ProfileFilterSaved(
        Result<infiltrator_core::filter::FilterReport, InfiltratorError>,
    ),
    // MRS rule-provider detail scan (Rules page providers tab).
    ScanMrsProviders,
    MrsDetailsReady(
        Result<Vec<crate::types::options::MrsProviderDetail>, InfiltratorError>,
    ),
    // Sync conflict key-level diff merge (Sync page).
    LoadSyncDiff(String),
    SyncDiffLoaded(Result<crate::types::options::SyncDiffBundle, InfiltratorError>),
    PickSyncDiffKey(String, bool),
    SetSyncDiffPicks(bool),
    ApplySyncDiffMerge,
    SyncDiffMerged(Result<String, InfiltratorError>),
    CloseSyncDiff,
    OpenConfigDirFinished(Result<(), InfiltratorError>),
    LoadKernels,
    KernelsLoaded(Result<Vec<VersionInfo>, InfiltratorError>),
    CheckCoreUpdate,
    CoreUpdateInfo(Result<String, InfiltratorError>), // Latest version string
    SetCoreChannel(String),
    DownloadCore(String),
    CoreDownloadProgress(CoreDownloadProgress, u64),
    CoreDownloadFinished(Result<String, InfiltratorError>, u64),
    CancelCoreDownload,
    DeleteKernel(String),
    SetDefaultKernel(String),
    KernelOperationFinished(Result<(), InfiltratorError>),
    FactoryReset,
    FactoryResetFinished(Result<(), InfiltratorError>),
    OpenConfigDir,
    FlushFakeIpCache,
    TestProxyDelay(String),
    TestGroupDelay(String),
    ProxyTested(String, Result<u64, InfiltratorError>),
    WindowClosed(window::Id),
    HideWindow,
    ShowWindow,
    UpdateRuntimeAutoRefresh(bool),
    RuntimePanelSettingsSaved(Result<(), InfiltratorError>),
    RuntimeRebuildFinished(Result<Arc<MihomoRuntime>, InfiltratorError>),
    ClearRebuildFlow,
    TogglePerfPanel,
    ToggleTheme,
    SetLanguage(String),
    ShowToast(String, ToastStatus),
    RemoveToast(usize),
    TestAllProxyDelays,
    AllProxyDelaysTested(Result<(usize, usize), InfiltratorError>),
    // ui-wave2-p: proxies page — expand/collapse one proxy-group card
    // (view-only UI state; flips AppState::proxy_groups_expanded).
    ToggleProxyGroupExpanded(String),
    // Doctor 体检面板（诊断域）：经内嵌 admin server 的 loopback HTTP 调用
    // /admin/api/doctor* 与 /admin/api/bootstrap，报告写回 diag.doctor。
    RunDoctor,
    DoctorReportReady(Result<crate::types::doctor::DoctorReport, InfiltratorError>),
    RunDoctorFix,
    DoctorFixApplied(Result<crate::types::doctor::DoctorFixReport, InfiltratorError>),
    RunBootstrap,
    BootstrapFinished(Result<crate::types::doctor::BootstrapReport, InfiltratorError>),
}

mod debug;
