//! Stable identities of native operation surfaces, shared by their authors and layout queries.
use iced::advanced::widget::Id;

pub(crate) enum InteractionRegion {
    RestoreReview,
    RestoreDetails,
    RestoreConfirm,
    RestoreCancel,
    TrafficObservation,
    TrafficRates,
    TrafficFailure,
    Confirmation,
    ConfirmationDetails,
    ConfirmationAccept,
    ConfirmationCancel,
    Connection,
    ConnectionGroups,
    ConnectionGroupingControls,
    ConnectionGroupFlat,
    ConnectionGroupProcess,
    ConnectionGroupHost,
    ConnectionSearch,
    ConnectionSearchClear,
    LogsSearch,
    LogsSearchClear,
    LogsResults,
    LogFollow,
    LogExportLaunch,
    LogExportDialog,
    LogExportStatus,
    LogExportDetails,
    LogExportPath,
    LogExportConfirm,
    LogExportCancel,
    LogExportRetry,
    Protocol,
    Speedtest,
    Palette,
    ProxyInspection,
    ProxyInspectionHistory,
    ProxyProbeSettings,
    ProxyProbeTimeout,
    ProxyGroupOrder,
    ProxyGroupOrderList,
    LanguageChoices,
    ModeFailure,
    ModeRetry,
    ModeDismiss,
    ModeSettings,
    TunPermissionAction,
    DoctorReport,
    DoctorRetry,
    DnsLeakCard,
    DnsLeakRun,
    DnsQueryDialog,
    DnsQueryTabs,
    DnsQueryName,
    DnsQueryRun,
    DnsQueryCancel,
    DnsQueryRecords,
    CacheDialog,
    CacheConfirm,
    CacheCancel,
    HostsEditor,
    HostsAddress,
    HostsDomain,
    HostsRows,
    HostsApply,
    RuleTraceReport,
    StatisticsInspector,
    StatisticsReview,
    StatisticsSummary,
    StatisticsTop,
    StatisticsInactive,
    StatisticsInspect,
    StatisticsCleanup,
    StatisticsReset,
    RuleListEditor,
    RuleListStatus,
    RuleListPreview,
    RuleListSave,
    RuleListDiscard,
    FilterTransaction,
    FilterAdvanced,
    FilterInclude,
    FilterExclude,
    FilterProtocols,
    FilterRenames,
    FilterStatus,
    FilterSave,
    FilterDiscard,
}
impl InteractionRegion {
    pub fn id(self) -> Id {
        Id::new(match self {
            Self::RestoreReview => "snapshot-restore-review",
            Self::RestoreDetails => "snapshot-restore-details",
            Self::RestoreConfirm => "snapshot-restore-confirm",
            Self::RestoreCancel => "snapshot-restore-cancel",
            Self::TrafficObservation => "traffic-observation",
            Self::TrafficRates => "traffic-rates",
            Self::TrafficFailure => "traffic-failure",
            Self::LogsSearch => "logs-search",
            Self::LogsSearchClear => "logs-search-clear",
            Self::LogsResults => "logs-results",
            Self::LogFollow => "logs-follow",
            Self::LogExportLaunch => "logs-export-launch",
            Self::LogExportDialog => "logs-export-dialog",
            Self::LogExportStatus => "logs-export-status",
            Self::LogExportDetails => "logs-export-details",
            Self::LogExportPath => "logs-export-path",
            Self::LogExportConfirm => "logs-export-confirm",
            Self::LogExportCancel => "logs-export-cancel",
            Self::LogExportRetry => "logs-export-retry",
            Self::DnsQueryDialog => "dns-query-dialog",
            Self::DnsQueryTabs => "dns-query-tabs",
            Self::DnsQueryName => "dns-query-name",
            Self::DnsQueryRun => "dns-query-run",
            Self::DnsQueryCancel => "dns-query-cancel",
            Self::DnsQueryRecords => "dns-query-records",
            Self::Confirmation => "confirmation-dialog",
            Self::ConfirmationDetails => "confirmation-details",
            Self::ConfirmationAccept => "confirmation-accept",
            Self::ConfirmationCancel => "confirmation-cancel",
            Self::Connection => "connection-inspection",
            Self::ConnectionGroups => "connection-groups",
            Self::ConnectionGroupingControls => "connection-grouping-controls",
            Self::ConnectionGroupFlat => "connection-group-flat",
            Self::ConnectionGroupProcess => "connection-group-process",
            Self::ConnectionGroupHost => "connection-group-host",
            Self::ConnectionSearch => "connection-search",
            Self::ConnectionSearchClear => "connection-search-clear",
            Self::Protocol => "protocol-node-editor",
            Self::Speedtest => "speedtest-details",
            Self::Palette => "command-palette",
            Self::ProxyInspection => "proxy-inspection",
            Self::LanguageChoices => "language-choices",
            Self::ModeFailure => "proxy-mode-failure",
            Self::ModeRetry => "proxy-mode-retry",
            Self::ModeDismiss => "proxy-mode-dismiss",
            Self::ModeSettings => "proxy-mode-settings",
            Self::DnsLeakCard => "dns-leak-report",
            Self::DnsLeakRun => "dns-leak-run",
            Self::CacheDialog => "dns-cache-confirmation",
            Self::CacheConfirm => "dns-cache-confirm",
            Self::CacheCancel => "dns-cache-cancel",
            Self::HostsEditor => "hosts-editor",
            Self::HostsAddress => "hosts-address",
            Self::HostsDomain => "hosts-domain",
            Self::HostsRows => "hosts-rows",
            Self::HostsApply => "hosts-apply",
            Self::StatisticsReview => "rules-statistics-review",
            Self::StatisticsInspector => "rules-statistics-inspector",
            Self::StatisticsSummary => "rules-statistics-summary",
            Self::StatisticsTop => "rules-statistics-top",
            Self::StatisticsInactive => "rules-statistics-inactive",
            Self::StatisticsInspect => "rules-statistics-inspect",
            Self::StatisticsCleanup => "rules-statistics-cleanup",
            Self::StatisticsReset => "rules-statistics-reset",
            Self::RuleTraceReport => "rule-trace-report",
            Self::RuleListEditor => "rule-list-editor",
            Self::RuleListStatus => "rule-list-status",
            Self::RuleListPreview => "rule-list-preview",
            Self::RuleListSave => "rule-list-save",
            Self::RuleListDiscard => "rule-list-discard",
            Self::FilterTransaction => "filter-transaction",
            Self::FilterAdvanced => "filter-advanced",
            Self::FilterInclude => "filter-include",
            Self::FilterExclude => "filter-exclude",
            Self::FilterProtocols => "filter-protocols",
            Self::FilterRenames => "filter-renames",
            Self::FilterStatus => "filter-status",
            Self::FilterSave => "filter-save",
            Self::FilterDiscard => "filter-discard",
            Self::DoctorReport => "doctor-observation",
            Self::DoctorRetry => "doctor-retry",
            Self::TunPermissionAction => "tun-permission-action",
            Self::ProxyGroupOrder => "proxy-group-order",
            Self::ProxyGroupOrderList => "proxy-group-order-list",
            Self::ProxyProbeTimeout => "proxy-probe-timeout",
            Self::ProxyProbeSettings => "proxy-probe-settings",
            Self::ProxyInspectionHistory => "proxy-inspection-history",
        })
    }
}
