//! The command-name vocabulary published in `CoreEvent` failures.
//!
//! Split out of the lifecycle application so the match that maps every
//! `CommandIntent` to its wire name stays readable next to the dispatch
//! worker that reports it.

use super::*;

pub(super) fn command_name(intent: &CommandIntent) -> &'static str {
    match intent {
        CommandIntent::StartCore => "start_core",
        CommandIntent::StopCore => "stop_core",
        CommandIntent::RestartCore => "restart_core",
        CommandIntent::PrepareServiceMode => "prepare_service_mode",
        CommandIntent::RepairPortConflicts => "repair_port_conflicts",
        CommandIntent::SetCoreLogLevel { .. } => "set_core_log_level",
        CommandIntent::SetTunStack { .. } => "set_tun_stack",
        CommandIntent::ProbeTunMtu => "probe_tun_mtu",
        CommandIntent::SwitchProfile { .. } => "switch_profile",
        CommandIntent::SetProxyMode { .. } => "set_proxy_mode",
        CommandIntent::SelectProxyNode { .. } => "select_proxy_node",
        CommandIntent::TestDelay { .. } => "test_delay",
        CommandIntent::RunSpeedtest { .. } => "run_speedtest",
        CommandIntent::RecordSpeedtestBandwidth { .. } => "record_speedtest_bandwidth",
        CommandIntent::RecordSpeedtestOutboundIp { .. } => "record_speedtest_outbound_ip",
        CommandIntent::SetSpeedtestConcurrency { .. } => "set_speedtest_concurrency",
        CommandIntent::CancelSpeedtest => "cancel_speedtest",
        CommandIntent::ToggleProxyGroupExpand { .. } => "toggle_proxy_group_expand",
        CommandIntent::SetProxyGroupExpanded { .. } => "set_proxy_group_expanded",
        CommandIntent::SetProxySortOrder { .. } => "set_proxy_sort_order",
        CommandIntent::ToggleFilterAlive { .. } => "toggle_filter_alive",
        CommandIntent::ToggleFavoriteProxy { .. } => "toggle_favorite_proxy",
        CommandIntent::SetProxyCompactView { .. } => "set_proxy_compact_view",
        CommandIntent::ReorderProxyGroups { .. } => "reorder_proxy_groups",
        CommandIntent::ResetProxyGroupOrder => "reset_proxy_group_order",
        CommandIntent::ReorderOverviewCards { .. } => "reorder_overview_cards",
        CommandIntent::ResetOverviewCardOrder => "reset_overview_card_order",
        CommandIntent::UpdateProfile { .. } => "update_profile",
        CommandIntent::UpdateAllSubscriptions => "update_all_subscriptions",
        CommandIntent::RestoreSubscriptionBackup { .. } => "restore_subscription_backup",
        CommandIntent::UpdateSubscriptionFetchSettings { .. } => {
            "update_subscription_fetch_settings"
        }
        CommandIntent::SetSubscriptionAutoReload { .. } => "set_subscription_auto_reload",
        CommandIntent::UpdateSubscriptionSchedule { .. } => "update_subscription_schedule",
        CommandIntent::ImportCustomNodeUri { .. } => "import_custom_node_uri",
        CommandIntent::SaveCustomNodeDraft { .. } => "save_custom_node_draft",
        CommandIntent::ScanDialerChains => "scan_dialer_chains",
        CommandIntent::UpdateCustomNodeDraftField { .. } => "update_custom_node_draft_field",
        CommandIntent::ResolveCertificateAuthority { .. } => "resolve_certificate_authority",
        CommandIntent::DeleteProfile { .. } => "delete_profile",
        CommandIntent::RefreshRuleProviders => "refresh_rule_providers",
        CommandIntent::CloseConnection { .. } => "close_connection",
        CommandIntent::CloseAllConnections => "close_all_connections",
        CommandIntent::ClearLogs => "clear_logs",
        CommandIntent::SetLogLevelFilter { .. } => "set_log_level_filter",
        CommandIntent::ClearDnsCache => "clear_dns_cache",
        CommandIntent::TestDnsLatency => "test_dns_latency",
        CommandIntent::TestDnsLeak => "test_dns_leak",
        CommandIntent::RunStunProbe => "run_stun_probe",
        CommandIntent::ApplyDnsSettings { .. } => "apply_dns_settings",
        CommandIntent::RunDoctorDiagnostics => "run_doctor_diagnostics",
        CommandIntent::RepairDoctorIssue { .. } => "repair_doctor_issue",
        CommandIntent::RepairAllDoctorIssues => "repair_all_doctor_issues",
        CommandIntent::ToggleTun { .. } => "toggle_tun",
        CommandIntent::SetTunAutoRoute { .. } => "set_tun_auto_route",
        CommandIntent::SetTunStrictRoute { .. } => "set_tun_strict_route",
        CommandIntent::SetSystemProxy { .. } => "set_system_proxy",
        CommandIntent::SetLanSharing { .. } => "set_lan_sharing",
        CommandIntent::SetLanSecurity { .. } => "set_lan_security",
        CommandIntent::SetIpv6Routing { .. } => "set_ipv6_routing",
        CommandIntent::ScanUwpApps => "scan_uwp_apps",
        CommandIntent::SetUwpAppExemption { .. } => "set_uwp_app_exemption",
        CommandIntent::SetAllUwpExemptions { .. } => "set_all_uwp_exemptions",
        CommandIntent::ApplyPac { .. } => "apply_pac",
        CommandIntent::RefreshNetworkRoaming => "refresh_network_roaming",
        CommandIntent::RepairNetworkRoutes => "repair_network_routes",
        CommandIntent::StartVpn => "start_vpn",
        CommandIntent::StopVpn => "stop_vpn",
        CommandIntent::RunPrivilegedNetworkRegression => "run_privileged_network_regression",
        CommandIntent::ToggleAppRouting { .. } => "toggle_app_routing",
        CommandIntent::SetAppRoutingMode { .. } => "set_app_routing_mode",
        CommandIntent::ToggleIncludeSystemApps { .. } => "toggle_include_system_apps",
        CommandIntent::SetAppRule { .. } => "set_app_rule",
        CommandIntent::SyncNow => "sync_now",
        CommandIntent::CreateBackupSnapshot => "create_backup_snapshot",
        CommandIntent::ResolveConflictKeepLocal => "resolve_conflict_keep_local",
        CommandIntent::ResolveConflictTakeRemote => "resolve_conflict_take_remote",
        CommandIntent::RestoreSnapshot { .. } => "restore_snapshot",
        CommandIntent::LoadSnapshotDiff { .. } => "load_snapshot_diff",
        CommandIntent::LoadSnapshotHistory => "load_snapshot_history",
        CommandIntent::PruneSnapshots { .. } => "prune_snapshots",
        CommandIntent::LoadProfileDocument { .. } => "load_profile_document",
        CommandIntent::SaveProfileDocument { .. } => "save_profile_document",
        CommandIntent::LoadProfileOptions { .. } => "load_profile_options",
        CommandIntent::SaveMixinOverlay { .. } => "save_mixin_overlay",
        CommandIntent::RefreshPublicIpProbe => "refresh_public_ip_probe",
        CommandIntent::RollbackCore => "rollback_core",
        CommandIntent::UpdateSetting { .. } => "update_setting",
        CommandIntent::CheckUpdates => "check_updates",
        CommandIntent::SimulateRuleTrace { .. } => "simulate_rule_trace",
        CommandIntent::SetRuleTracerContext { .. } => "set_rule_tracer_context",
        CommandIntent::ApplyTracerRuleOverride { .. } => "apply_tracer_rule_override",
        CommandIntent::ResetRuleHitCounters => "reset_rule_hit_counters",
        CommandIntent::UnpackRuleProvider { .. } => "unpack_rule_provider",
        CommandIntent::PurgeRuleProviderCache => "purge_rule_provider_cache",
        CommandIntent::ToggleRuleEnabled { .. } => "toggle_rule_enabled",
        CommandIntent::MoveRule { .. } => "move_rule",
        CommandIntent::AddCustomRule { .. } => "add_custom_rule",
        CommandIntent::ApplyGameRoutingPresets { .. } => "apply_game_routing_presets",
        CommandIntent::UpgradeGeoDatabases => "upgrade_geo_databases",
        CommandIntent::ApplyRulesJsonDocument { .. } => "apply_rules_json_document",
        CommandIntent::SaveSubscriptionFilter { .. } => "save_subscription_filter",
        CommandIntent::ImportSubscription { .. } => "import_subscription",
        CommandIntent::PreviewProfileAggregation { .. } => "preview_profile_aggregation",
        CommandIntent::CreateAggregatedProfile { .. } => "create_aggregated_profile",
        CommandIntent::SaveAggregationTemplate { .. } => "save_aggregation_template",
        CommandIntent::DeleteAggregationTemplate { .. } => "delete_aggregation_template",
        CommandIntent::ReAggregateProfile { .. } => "reaggregate_profile",
    }
}
