//! Pure-spec tray tests: menu tree layout, localized labels, payload
//! codecs and event→intent resolution. Mounted as a nested module of
//! `tray_tests.rs` (same red lines: no D-Bus, no ksni/muda spawn, no
//! network, no mihomo).

use super::*;
use crate::tray::menu::build_tray_spec;
use crate::tray::spec::{
    TRAY_ACTION_ACTIVATE_PROFILE, TRAY_ACTION_CANCEL_CORE_DOWNLOAD, TRAY_ACTION_CANCEL_SYNC,
    TRAY_ACTION_CHECK_CORE_UPDATE, TRAY_ACTION_FACTORY_RESET, TRAY_ACTION_FLUSH_FAKEIP,
    TRAY_ACTION_INFO_ADMIN, TRAY_ACTION_INFO_CONTROLLER, TRAY_ACTION_INFO_DOWNLOAD,
    TRAY_ACTION_INFO_KERNEL_DEFAULT, TRAY_ACTION_INFO_KERNEL_STATUS,
    TRAY_ACTION_INFO_KERNEL_VERSION, TRAY_ACTION_INFO_MODE, TRAY_ACTION_INFO_STATUS,
    TRAY_ACTION_INFO_SYNC, TRAY_ACTION_MODE_DIRECT, TRAY_ACTION_MODE_GLOBAL, TRAY_ACTION_MODE_RULE,
    TRAY_ACTION_MODE_SCRIPT, TRAY_ACTION_NAVIGATE_SYNC, TRAY_ACTION_NO_PROFILES,
    TRAY_ACTION_NO_PROXIES, TRAY_ACTION_QUIT, TRAY_ACTION_SELECT_GLOBAL_PROXY,
    TRAY_ACTION_SELECT_PROXY, TRAY_ACTION_SET_DEFAULT_KERNEL, TRAY_ACTION_SET_PROFILE_AUTO_UPDATE,
    TRAY_ACTION_SHOW, TRAY_ACTION_SYNC_DOWNLOAD, TRAY_ACTION_SYNC_UPLOAD,
    TRAY_ACTION_TOGGLE_AUTOSTART, TRAY_ACTION_TOGGLE_SYSTEM_PROXY, TRAY_ACTION_TOGGLE_THEME,
    TRAY_ACTION_TOGGLE_TUN, TRAY_ACTION_UNINSTALL_KERNEL, TRAY_ACTION_UPDATE_ALL_PROFILES,
    TRAY_SUBMENU_INFO, TRAY_SUBMENU_KERNEL, TRAY_SUBMENU_MODE, TRAY_SUBMENU_PROFILES,
    TRAY_SUBMENU_PROXIES, TRAY_SUBMENU_PROXY_GROUP_BASE, TRAY_SUBMENU_PROXY_MORE_BASE,
    TRAY_SUBMENU_SYNC, TrayCoreStatus, TrayEvent, TrayEventContext, TrayIntent, TrayMenuItem,
    decode_pair_payload, encode_pair_payload, resolve_tray_event_in,
};

#[path = "tray_spec_menu_tests/every.rs"]
mod every;
#[path = "tray_spec_menu_tests/payload.rs"]
mod payload;
#[path = "tray_spec_menu_tests/resolve.rs"]
mod resolve;
#[path = "tray_spec_menu_tests/spec.rs"]
mod spec;
