[package]
name = "infiltrator-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "infiltrator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
infiltrator-contract = { path = "../infiltrator-contract" }
infiltrator-ports = { path = "../infiltrator-ports" }
dav-client = { path = "../mihomo-dav-sync/dav-client" }
infiltrator-core = { path = "../infiltrator-core" }
infiltrator-domain = { path = "../infiltrator-domain" }
infiltrator-http = { path = "../infiltrator-http" }
mihomo-api = { path = "../mihomo-api" }
mihomo-config = { path = "../mihomo-config" }
mihomo-platform = { path = "../mihomo-platform" }
mihomo-version = { path = "../mihomo-version" }
serde = { workspace = true }
serde_json = { workspace = true }
state-store = { path = "../mihomo-dav-sync/state-store" }
sync-engine = { path = "../mihomo-dav-sync/sync-engine" }
tokio = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
tempfile = { workspace = true }
